apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - image: nginx:latest
      name: web-pod
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/log/nginx
          name: hostpath-volume
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /var/volume