apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: init
  name: init
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.35
    name: init
    resources: {}
  initContainers:
    - name: init-svc
      image: busybox:1.35
      command:
        - sh
        - -c
        - until nslookup init-svc; do echo waiting for svc; sleep 2; done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
